language: en-US
early_access: true
reviews:
  profile: assertive
  request_changes_workflow: true
  review_status: true
  poem: false
  collapse_walkthrough: true
  sequence_diagrams: true
  path_filters: []
  path_instructions: []
  abort_on_close: true
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: []
    labels: []
    drafts: false
  tools:
    github-checks:
      enabled: false

chat:
  auto_reply: true
